server:
  port: 8101


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: monitoring
          uri: http://localhost:8182
          predicates:
            - Path=/api/monitoring/**
        - id: quality_service
          uri: http://localhost:8183
          predicates:
            - Path=/api/quality/**
