server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: monitoring
          uri: http://localhost:8082
          predicates:
            - Path=/api/monitoring/**
        - id: quality_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/quality/**
